SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT DEPTNO, DNAME FROM DEPT;
SELECT * FROM DEPT;
INSERT INTO DEPT VALUES(50, '총무부', '서울');
UPDATE DEPT SET LOC='부산' WHERE DNAME='총무부';
DELETE FROM DEPT WHERE DEPTNO=50;

-- DDL(Data Definition Language)
-- DROP
DROP TABLE DEPT01;
DROP TABLE DEPTO1;

-- Create
CREATE TABLE DEPT01(
  DEPTNO NUMBER(4),   -- 숫자 4자리
  DNAME VARCHAR2(10), -- 문자열 10자리
  LOC VARCHAR2(9)     -- 문자열 9자리
);

DESC DEPT01;
-- DEPT01 을 표현해주는 구문 (DESCRIBE 약자 : DESC)
-- DESC DEPT01; 하고 뒤에 주석 달아놓고 실행시키면 오류발생한다..!!

-- ALTER
ALTER TABLE DEPT01
MODIFY(DNAME VARCHAR2(30));

-- RENAME : 이름 변경
RENAME DEPT01 TO DEPT02;
DESC DEPT02;

SELECT * FROM DEPT02;
INSERT INTO DEPT02 VALUES(10,'개발부','서울');
--DELETE FROM DEPT02;
-- DEPT02에 있는 모든 데이터 삭제
--ROLLBACK;
-- ROLLBACK 롤백 : 데이터 삭제하고 난 뒤 롤백을 하면 다시 그 전으로 돌아간다.

-- TRUNCATE : 데이터 공간을 삭제, 테이블은 삭제가 안되고 데이터만 삭제 (DELETE랑 다름,,)
TRUNCATE TABLE DEPT02;

-- DROP : 테이블 자체가 다 날라간다.
DROP TABLE DEPT02;


-- DCL(DATA CONTROL DANGUAGE) : GRANT, REVOKE
-- GRANT : 권한 부여
-- REVOKE : 권한 취소



SELECT * FROM TAB;

SELECT * FROM DEPT01;
DESC DEPT01;
INSERT INTO DEPT01 VALUES(NULL,'개발부','서울');

SELECT * FROM DEPT;
--INSERT INTO DEPT VALUES(NULL,'개발부','서울');
-- 오류 보고 ) ORA-01400: cannot insert NULL into ("SCOTT"."DEPT"."DEPTNO")
-- DEPTNO 칼럼에 NULL을 넣을 수 없다.
INSERT INTO DEPT VALUES(50,'개발부','서울');
DESC DEPT;



-- 데이터타입 : NUMBER, DATE, VARCHAR2
-- BOOLEAN 타입은 없지만 비슷하게 CHAR형으로 만들 수 있다.
CREATE TABLE ITEMS(
  ITEM_NO NUMBER(3),
  ISACTIVE CHAR(1) CHECK(ISACTIVE IN ('Y', 'N'))
  -- 제약조건을 넣어준다. 제약조건 : NOT NULL, PRIMARY KEY, FOREIGN KEY, UNIQUE, CHECK
  -- ISACTIVE에 Y 또는 N 문자열만 들어오는지 확인하는 제약조건 넣음
);

SELECT * FROM ITEMS;
INSERT INTO ITEMS VALUES(101, 'Y');
INSERT INTO ITEMS VALUES(101, 'N');
INSERT INTO ITEMS VALUES(102, 'F'); -- 오류 발생한다! Y 또는 N 문자열만 와야하는 제약조건을 집어넣었기 때문에 F문자열 넣으려고 하니 오류발생



-- 2.4 데이터 조회를 위한 SELECT 문
-- 형식 : SELECT * (COLUM_NAME) FROM TABLE_NAME
SELECT * FROM DEPT;
SELECT * FROM EMP;
DESC EMP;
SELECT EMPNO, ENAME FROM EMP;



-- 산술 연산자
SELECT ENAME, SAL, SAL*12, COMM, SAL*12+COMM FROM EMP;

-- NVL(NULL VALUE) 함수는 NULL을 0 또는 다른 값으로 변환할 수 있다.
SELECT ENAME, SAL, SAL*12, COMM, SAL*12+NVL(COMM,0) FROM EMP;

SELECT ENAME, SAL, SAL*12, COMM, SAL*12+NVL(COMM,0) AS ANNSAL FROM EMP;

SELECT ENAME, SAL, SAL*12, COMM, SAL*12+NVL(COMM,0) "A N N S A L" FROM EMP;

SELECT ENAME, SAL, SAL*12, COMM, SAL*12+NVL(COMM,0) "연봉" FROM EMP;



-- Concatenation 연산자
SELECT ENAME, JOB FROM EMP;
SELECT ENAME || ' IS A ' || JOB FROM EMP;


-- DISTINCT 키워드
SELECT * FROM EMP;
SELECT DEPTNO FROM EMP;
-- DEPNO 컬럼에 중복된 값이 존재한다.
SELECT DISTINCT DEPTNO FROM EMP;
-- DEPNO 컬럼에서 값이 중복되지 않게 한번씩만 값 출력된다.
