-- 사용자(USER04/PWD) 생성하기
CREATE USER USER04 IDENTIFIED BY PWD;

--USER04에게 ROLE 부여
GRANT CONNECT, RESOURCE TO USER04;


-- 사용자 롤 정의하기
CREATE ROLE MROLE; -- 롤 생성
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW TO MROLE;
-- MROLE은 GRANT 받음으로서 3개의 시스템 권한을 가지게 된다.

CREATE USER USER05 IDENTIFIED BY PWD; -- USER05 사용자 생성
GRANT MROLE TO USER05; -- 3개의 시스템권한이 들어있는 MROLE 롤을 한번만 부여함.
REVOKE MROLE FROM USER05;


-- 동의어 생성 및 제거
DROP TABLE SYSTBL;
CREATE TABLE SYSTBL(
    ENAME VARCHAR2(20)
);

INSERT INTO SYSTBL VALUES('전수빈');

SELECT * FROM SYSTBL;

-- 객체 권한 부여
GRANT SELECT ON SYSTBL TO SCOTT; -- SCOTT 계정에게 SYSTBL 접근할 수 있는 권한 부여해줌

GRANT CREATE SYNONYM TO SCOTT;














