SHOW USER;
-- USER이(가) "USER10"입니다. 출력

-- CREATE TABLE 테이블 생성하기
DROP TABLE EMP01;

CREATE TABLE EMP01(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2)
);

SELECT * FROM EMP01;